# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ecfe1d2bfa379c0c4120d94470ba1baeac7879ce78dcfc51f48f06a936100ccf62332bd50d60cb9334d00bc5b4dfcc2e28f01c914534753f05c81044d3b61eb2

test:
  secret_key_base: 0c5e2956725a26e50d25c61b7cd678e38b57d966558fb56a11c7988c71109c174d3f5b14d0ccfc75226c4264e0307e9e1dff6bfb09ad7c3ad6b3d057c1df3c1c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
